#if !canImport(ObjectiveC)
import XCTest

extension AddressTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddressTests = [
        ("testBaseSerializeConsistency", testBaseSerializeConsistency),
        ("testBech32Parsing", testBech32Parsing),
        ("testBip3212Base", testBip3212Base),
        ("testBip3212Enterprise", testBip3212Enterprise),
        ("testBip3212Pointer", testBip3212Pointer),
        ("testBip3212Reward", testBip3212Reward),
        ("testBip3215Base", testBip3215Base),
        ("testBip3215Byron", testBip3215Byron),
        ("testBip3215Enterprise", testBip3215Enterprise),
        ("testBip3215Pointer", testBip3215Pointer),
        ("testBip3224Base", testBip3224Base),
        ("testBip3224Enterprise", testBip3224Enterprise),
        ("testBip3224Pointer", testBip3224Pointer),
        ("testByronMagicParsing", testByronMagicParsing),
        ("testEnterpriseSerializeConsistency", testEnterpriseSerializeConsistency),
        ("testParseRedeemAddress", testParseRedeemAddress),
        ("testPtrSerializeConsistency", testPtrSerializeConsistency),
        ("testRewardSerializeConsistency", testRewardSerializeConsistency),
    ]
}

extension CoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CoreTests = [
        ("testLinearFee", testLinearFee),
        ("testNativeScriptHash", testNativeScriptHash),
        ("testTransactionWitnessSet", testTransactionWitnessSet),
        ("testValue", testValue),
    ]
}

extension CryptoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CryptoTests = [
        ("testChaincodeGen", testChaincodeGen),
        ("testNonceHash", testNonceHash),
        ("testNonceIdentity", testNonceIdentity),
        ("testXprv128Test", testXprv128Test),
    ]
}

extension FeesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeesTests = [
        ("testTxMultiUtxo", testTxMultiUtxo),
        ("testTxRegisterStake", testTxRegisterStake),
        ("testTxSimpleByronUtxo", testTxSimpleByronUtxo),
        ("testTxSimpleUtxo", testTxSimpleUtxo),
        ("testTxWithdrawal", testTxWithdrawal),
    ]
}

extension MetadataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MetadataTests = [
        ("testBinaryEncoding", testBinaryEncoding),
        ("testJsonEncodingBasic", testJsonEncodingBasic),
        ("testJsonEncodingDetailed", testJsonEncodingDetailed),
        ("testJsonEncodingDetailedComplexKey", testJsonEncodingDetailedComplexKey),
        ("testJsonEncodingNoConversions", testJsonEncodingNoConversions),
    ]
}

extension TransactionBodyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransactionBodyTests = [
        ("testTransactionBody", testTransactionBody),
    ]
}

extension TransactionBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransactionBuilderTests = [
        ("testBuildTxBurnEmptyAssets", testBuildTxBurnEmptyAssets),
        ("testBuildTxBurnLessThanMinAda", testBuildTxBurnLessThanMinAda),
        ("testBuildTxExactAmount", testBuildTxExactAmount),
        ("testBuildTxExactChange", testBuildTxExactChange),
        ("testBuildTxInsufficientDeposit", testBuildTxInsufficientDeposit),
        ("testBuildTxLeftoverAssets", testBuildTxLeftoverAssets),
        ("testBuildTxWithCerts", testBuildTxWithCerts),
        ("testBuildTxWithChange", testBuildTxWithChange),
        ("testBuildTxWithInputs", testBuildTxWithInputs),
        ("testBuildTxWithNativeAssetsChange", testBuildTxWithNativeAssetsChange),
        ("testBuildTxWithoutChange", testBuildTxWithoutChange),
    ]
}

extension UtilsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilsTests = [
        ("testCompareValues", testCompareValues),
        ("testMinAdaValueNoMultiasset", testMinAdaValueNoMultiasset),
        ("testMinAdaValueOnePolicyOne0CharAsset", testMinAdaValueOnePolicyOne0CharAsset),
        ("testMinAdaValueOnePolicyOne0CharAssetDatumHash", testMinAdaValueOnePolicyOne0CharAssetDatumHash),
        ("testMinAdaValueOnePolicyOne1CharAsset", testMinAdaValueOnePolicyOne1CharAsset),
        ("testMinAdaValueOnePolicyThree1CharAssets", testMinAdaValueOnePolicyThree1CharAssets),
        ("testMinAdaValueOnePolicyThree32CharAssetsDatumHash", testMinAdaValueOnePolicyThree32CharAssetsDatumHash),
        ("testMinAdaValueThreePolicies961CharAssets", testMinAdaValueThreePolicies961CharAssets),
        ("testMinAdaValueTwoPoliciesOne0CharAsset", testMinAdaValueTwoPoliciesOne0CharAsset),
        ("testMinAdaValueTwoPoliciesOne0CharAssetDatumHash", testMinAdaValueTwoPoliciesOne0CharAssetDatumHash),
        ("testMinAdaValueTwoPoliciesOne1CharAsset", testMinAdaValueTwoPoliciesOne1CharAsset),
        ("testSubtractValues", testSubtractValues),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AddressTests.__allTests__AddressTests),
        testCase(CoreTests.__allTests__CoreTests),
        testCase(CryptoTests.__allTests__CryptoTests),
        testCase(FeesTests.__allTests__FeesTests),
        testCase(MetadataTests.__allTests__MetadataTests),
        testCase(TransactionBodyTests.__allTests__TransactionBodyTests),
        testCase(TransactionBuilderTests.__allTests__TransactionBuilderTests),
        testCase(UtilsTests.__allTests__UtilsTests),
    ]
}
#endif
