#if !canImport(ObjectiveC)
import XCTest

extension AddressTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddressTests = [
        ("testBaseSerializeConsistency", testBaseSerializeConsistency),
        ("testBech32Parsing", testBech32Parsing),
        ("testBip3212Base", testBip3212Base),
        ("testBip3212Enterprise", testBip3212Enterprise),
        ("testBip3212Pointer", testBip3212Pointer),
        ("testBip3212Reward", testBip3212Reward),
        ("testBip3215Base", testBip3215Base),
        ("testBip3215Byron", testBip3215Byron),
        ("testBip3215Enterprise", testBip3215Enterprise),
        ("testBip3215Pointer", testBip3215Pointer),
        ("testBip3224Base", testBip3224Base),
        ("testBip3224Enterprise", testBip3224Enterprise),
        ("testBip3224Pointer", testBip3224Pointer),
        ("testByronMagicParsing", testByronMagicParsing),
        ("testEnterpriseSerializeConsistency", testEnterpriseSerializeConsistency),
        ("testParseRedeemAddress", testParseRedeemAddress),
        ("testPtrSerializeConsistency", testPtrSerializeConsistency),
        ("testRewardSerializeConsistency", testRewardSerializeConsistency),
    ]
}

extension CardanoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CardanoTests = [
        ("testLinearFee", testLinearFee),
        ("testMoveInstantaneousReward", testMoveInstantaneousReward),
        ("testNativeScriptHash", testNativeScriptHash),
        ("testTransactionWitnessSet", testTransactionWitnessSet),
        ("testValue", testValue),
    ]
}

extension CryptoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CryptoTests = [
        ("testChaincodeGen", testChaincodeGen),
        ("testNonceHash", testNonceHash),
        ("testNonceIdentity", testNonceIdentity),
        ("testXprv128Test", testXprv128Test),
    ]
}

extension FeesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeesTests = [
        ("testTxMultiUtxo", testTxMultiUtxo),
        ("testTxRegisterStake", testTxRegisterStake),
        ("testTxSimpleByronUtxo", testTxSimpleByronUtxo),
        ("testTxSimpleUtxo", testTxSimpleUtxo),
        ("testTxWithdrawal", testTxWithdrawal),
    ]
}

extension MetadataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MetadataTests = [
        ("testAllegraMetadata", testAllegraMetadata),
        ("testBinaryEncoding", testBinaryEncoding),
        ("testJsonEncodingBasic", testJsonEncodingBasic),
        ("testJsonEncodingDetailed", testJsonEncodingDetailed),
        ("testJsonEncodingDetailedComplexKey", testJsonEncodingDetailedComplexKey),
        ("testJsonEncodingNoConversions", testJsonEncodingNoConversions),
    ]
}

extension TransactionBodyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransactionBodyTests = [
        ("testTransactionBody", testTransactionBody),
    ]
}

extension TransactionBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransactionBuilderTests = [
        ("testBuildTxBurnEmptyAssets", testBuildTxBurnEmptyAssets),
        ("testBuildTxBurnLessThanMinAda", testBuildTxBurnLessThanMinAda),
        ("testBuildTxExactAmount", testBuildTxExactAmount),
        ("testBuildTxExactChange", testBuildTxExactChange),
        ("testBuildTxInsufficientDeposit", testBuildTxInsufficientDeposit),
        ("testBuildTxLeftoverAssets", testBuildTxLeftoverAssets),
        ("testBuildTxWithCerts", testBuildTxWithCerts),
        ("testBuildTxWithChange", testBuildTxWithChange),
        ("testBuildTxWithInputs", testBuildTxWithInputs),
        ("testBuildTxWithNativeAssetsChange", testBuildTxWithNativeAssetsChange),
        ("testBuildTxWithoutChange", testBuildTxWithoutChange),
        ("testTransactionBuilder", testTransactionBuilder),
    ]
}

extension UtilsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilsTests = [
        ("testCompareValues", testCompareValues),
        ("testNoTokenMinimum", testNoTokenMinimum),
        ("testOnePolicyOneLargestName", testOnePolicyOneLargestName),
        ("testOnePolicyOneSmallestName", testOnePolicyOneSmallestName),
        ("testOnePolicyOneSmallName", testOnePolicyOneSmallName),
        ("testOnePolicyThreeLargestNames", testOnePolicyThreeLargestNames),
        ("testOnePolicyThreeSmallNames", testOnePolicyThreeSmallNames),
        ("testSubtractValues", testSubtractValues),
        ("testThreePolicies99SmallNames", testThreePolicies99SmallNames),
        ("testTwoPoliciesOneSmallestName", testTwoPoliciesOneSmallestName),
        ("testTwoPoliciesTwoSmallNames", testTwoPoliciesTwoSmallNames),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AddressTests.__allTests__AddressTests),
        testCase(CardanoTests.__allTests__CardanoTests),
        testCase(CryptoTests.__allTests__CryptoTests),
        testCase(FeesTests.__allTests__FeesTests),
        testCase(MetadataTests.__allTests__MetadataTests),
        testCase(TransactionBodyTests.__allTests__TransactionBodyTests),
        testCase(TransactionBuilderTests.__allTests__TransactionBuilderTests),
        testCase(UtilsTests.__allTests__UtilsTests),
    ]
}
#endif
