#if !canImport(ObjectiveC)
import XCTest

extension CardanoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CardanoTests = [
        ("testInit", testInit),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CardanoTests.__allTests__CardanoTests),
    ]
}
#endif
