#if !canImport(ObjectiveC)
import XCTest

extension AccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccountTests = [
        ("testAddressIsSame", testAddressIsSame),
        ("testBaseAddress", testBaseAddress),
    ]
}

extension AddressManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddressManagerTests = [
        ("testAccounts", testAccounts),
        ("testExtended", testExtended),
        ("testFetch", testFetch),
        ("testGet", testGet),
        ("testGetCached", testGetCached),
        ("testNew", testNew),
    ]
}

extension CardanoBalanceApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CardanoBalanceApiTests = [
        ("testAdaInAccount", testAdaInAccount),
        ("testAdaInAccountUpdate", testAdaInAccountUpdate),
        ("testAdaInAddress", testAdaInAddress),
    ]
}

extension CardanoSendApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CardanoSendApiTests = [
        ("testSendAdaFromAccount", testSendAdaFromAccount),
        ("testSendAdaFromAddresses", testSendAdaFromAddresses),
    ]
}

extension CardanoTxApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CardanoTxApiTests = [
        ("testGetTransaction", testGetTransaction),
        ("testSignAndSubmit", testSignAndSubmit),
        ("testSubmit", testSubmit),
    ]
}

extension KeychainTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeychainTests = [
        ("testAccounts", testAccounts),
        ("testAddAccount", testAddAccount),
        ("testInit", testInit),
        ("testSign", testSign),
    ]
}

extension UtxoProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtxoProviderTests = [
        ("testGetForAddresses", testGetForAddresses),
        ("testGetForTransaction", testGetForTransaction),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccountTests.__allTests__AccountTests),
        testCase(AddressManagerTests.__allTests__AddressManagerTests),
        testCase(CardanoBalanceApiTests.__allTests__CardanoBalanceApiTests),
        testCase(CardanoSendApiTests.__allTests__CardanoSendApiTests),
        testCase(CardanoTxApiTests.__allTests__CardanoTxApiTests),
        testCase(KeychainTests.__allTests__KeychainTests),
        testCase(UtxoProviderTests.__allTests__UtxoProviderTests),
    ]
}
#endif
